baseURL = "https://www.mokbel.io/"
languageCode = "en-us"
title = "George Mokbel's website - mokbel.io"
canonifyURLs = true
disableHugoGeneratorInject = true
disableKinds = ["taxonomy", "taxonomyTerm"]

[params]
    brand = "mokbel.io"
    github = "https://github.com/1gm"
    reddit = "https://www.reddit.com/user/mokbel"
    linkedin = "https://www.linkedin.com/in/gmokbel/"
    youtube = "https://youtube.com/GeorgeGoesAcoustic"